### ISSUE TITLE
Action lint fails occasionally - fatal error: concurrent map writes

### ISSUE THREAD

**Issue by zilinjak** [rhysd/actionlint#370]
Hello,
when using rhysd/actionlint:latest docker image to analyze workflows- [https://hub.docker.com/r/rhysd/actionlint](https://hub.docker.com/r/rhysd/actionlint)

The action sometimes fails out of nowhere without any reason. The log can be seen [here](https://pastebin.com/aZBUFYWL)

Thanks for any advices

**Comment by ReinAchten-TomTom** [comment]
We notice the same issue and for whatever reason we've started to see it more often recently.

It's a bug (a race condition to be specific) in actionlint that merely happens when a custom error message format is provided through `-format`. The map being accessed concurrently is `ErrorFormatter.rules` (see [here](https://github.com/rhysd/actionlint/blob/373b470ba05b31378c7bce94c2d570adadabd75c/error.go#L255)).

We've noticed at least the following race condition regarding this map when [RegisterRule](https://github.com/rhysd/actionlint/blob/373b470ba05b31378c7bce94c2d570adadabd75c/error.go#L319) is called from multiple concurrent [check](https://github.com/rhysd/actionlint/blob/373b470ba05b31378c7bce94c2d570adadabd75c/linter.go#L469C4-L469C4) functions calls.

**Comment by ReinAchten-TomTom** [comment]
@rhysd is this something you could look into or suggest how to best fix? I'm not proficient in golang, but can give it a try if you provide a hint. Thnx! :pray:

**Comment by rhysd** [comment]
Let me check this issue this weekend. I don't have enough time to handle all projects for now.

**Comment by noahnu** [comment]
I've run into this as well. Using an older version of actionlint in the meantime. Looking into the issue, it seems switching to `sync.Map` for the rules map may help?

**Comment by rhysd** [comment]
I apologize for the delay. I could fix this at d80a2a3. @ReinAchten-TomTom's comment was so helpful to fix this.

**Comment by maikelvdh** [comment]
@rhysd thanks a lot for addressing this problem! is there any plan to release a new version soon? 🙏
