### ISSUE TITLE
runner property "environment" is not defined in object type

### ISSUE THREAD

**Issue by acalcutt** [rhysd/actionlint#412]
I am trying to use runner.environment in my workflow, which works. However actionlint gives me the following error
```
.github/workflows/node-ci.yml:168:13: property "environment" is not defined in object type {arch: string; debug: string; name: string; os: string; temp: string; tool_cache: string} [expression]
    |
168 |         if: runner.environment == 'github-hosted'
```

Researching the reason why I notice running.environment has not yet been documented. 
https://github.com/orgs/community/discussions/118413
https://github.com/github/docs/issues/32443
so I am wondering if that is related

**Comment by rhysd** [comment]
That's because it is undocumented. Once we understand it is a part of public API, we can easily add it to actionlint.

Previously there were several private context properties and such properties were removed silently. So undocumented properties are basically not recognized by actionlint.

https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context

**Comment by rhysd** [comment]
As per https://github.com/github/docs/issues/32443, it seems a public API. So I will add the property.

**Comment by acalcutt** [comment]
Thanks for including this!

**Comment by wyardley** [comment]
I see the same thing for `inputs.environment` -- does need a similar fix?

e.g.
```yaml
jobs:
  foo:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
```
