### ISSUE TITLE
actions/download-artifact for GHE environment

### ISSUE THREAD

**Issue by andreineculau** [rhysd/actionlint#468]
using v3 fails actionlint with

> the runner of "actions/upload-artifact@v3" action is too old to run on GitHub Actions. update the action's version to fix this issue [action]

but actions/upload-artifact@v4 cannot be used on GHES

> Warning: Artifact upload failed with error: GHESNotSupportedError: @actions/artifact v2.0.0+, upload-artifact@v4+ and download-artifact@v4+ are not currently supported on GHES..

Can we add a special condition?

**Comment by andreineculau** [comment]
see https://github.com/actions/upload-artifact?tab=readme-ov-file#v4---whats-new

**Comment by nkhoidang** [comment]
Same for artifact-upload

**Comment by rhysd** [comment]
I have no idea because I don't have a GHE environment with GitHub Actions enabled. One obvious workaround for this is ignoring the erorr by regular expressions as desribed in the [v1.7.4 releae note](https://github.com/rhysd/actionlint/releases/tag/v1.7.4).

Before considering to add some special handling for this, I'd like to ask some questions to understand the situation better.

- `actions/upload-artifact@v3` will be unavailable soon because [node16 will be dropped on Nov. 12](https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/).
  - Will `actions/upload-artifact@v4` support GHE in the time frame?
  - Or will GHE continue to support `node16` runner with `actions/upload-artifact@v4` being unsupported in long term?
- Is there any good document which describes what runners are supported on GHE (if supported runners are different from the github.com environment)?

**Comment by rhysd** [comment]
I found `actions/upload-artifact@v3-node20`. Is it what you should use?

https://github.com/actions/upload-artifact/releases/tag/v3-node20

**Comment by andreineculau** [comment]
> One obvious workaround for this is ignoring the erorr by regular expressions as desribed in the [v1.7.4 releae note](https://github.com/rhysd/actionlint/releases/tag/v1.7.4).

Cool. What we have done temporarily is to use the commit hash pointing to the current v3 (at the expense of maybe failing to keep up to the date with v3 patches). I didn't know about the `v3-node20` versions 🙌

> I'm a bit confused because they announce that actions/upload-artifact@v4 doesn't support GHE but https://github.com/actions/upload-artifact/issues/635.

There's some info related to roadmap here https://github.com/actions/upload-artifact/issues/537 - tl;dr v3 will be deprecated but will still run on GHES moving forward, with the expectation that v4 will be supported Q1 2025

> Is there any good document which describes what runners are supported on GHE (if supported runners are different from the github.com environment)?

Not sure what you mean. On GHES you only have self-hosted runners AFAIK, so anything goes.

**Comment by rhysd** [comment]
> at the expense of maybe failing to keep up to the date with v3 patches

Yes. I don't know how it is maintained. However `v3` is deprecated and I don't think new features will be added.

> There's some info related to roadmap here https://github.com/actions/upload-artifact/issues/537 - tl;dr v3 will be deprecated but will still run on GHES moving forward, with the expectation that v4 will be supported Q1 2025

Thank you for the information. Then I believe `v3/node20` branch will be maintained until `v4` supports GHES. `v3` cannot be upgraded to node20 runner because it breaks the compatibility. And `v4` is not supporting GHES yet. Maintaining `v3/node20` is the only way to support GHES.

> Not sure what you mean. On GHES you only have self-hosted runners AFAIK, so anything goes.

I didn't know that GHES only supports self-hosted runners. As I said above, I don't have GHES environment hence I don't know the specs at all. Thanks for explaining that :+1:

**Comment by rhysd** [comment]
I'm closing this because `actions/download-artifact@v3-node20` is the current solution.
