### ISSUE TITLE
Support eslint

### ISSUE THREAD

**Issue by massongit** [rhysd/actionlint#55]
I think supporting `eslint` as well as `shellcheck` makes it easier to inspect code written using `actions/github-script`.

**Comment by rhysd** [comment]
Thanks for the suggestion.

The idea that providing a check for `actions/github-script` basically makes sense to me. However I think there are some challenges if we adopt eslint.

- eslint is not globally installed usually. It is installed as dependency of local project and usually not installed in `$PATH` directory. actionlint cannot know where the `eslint` command exists. And asking non-JS users to install eslint globally only for actionlint is hard.
- eslint usually requires a config file `eslintrc` otherwise eslint checks nothing. User needs to write up their configuration. It's hard to write up and maintain eslint config only for checking GitHub Actions workflows (especially for non-JS people).
- eslint is not designed for linting a small code snippet. It is designed for linting (possibly large) JavaScript project. I think the design does not fit to actionlint's usage. Many code style checks are not useful for small snippets and some false positives would be reported (for example, `github-script` defines `github` variable implicitly).

For above reasons, I think it's hard to support `github-script` linting with eslint.

**Comment by massongit** [comment]
I understand that it is difficult to support `eslint` and `actions/github-script`.
I close this issue.

**Comment by nomeata** [comment]
Would it be possible to support this with implicitly wrapping the body in the right function declaration, roughly like in https://github.com/actions/github-script#use-scripts-with-jsdoc-support?

Having some kind of syntax and ideally type checking locally would avoid so many problems I had :-]
